### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by IanPouncey** [bbc/gel-test-docs#10]
https://bbc.github.io/gel/foundations/iconography/

**Comment by IanPouncey** [comment]
## Extrapolation from GEL technical recommendations

### Required

* SVG icons must take the focusable="false" attribution to remove them from focus order in some versions of IE and Edge

### Recommended

* It is not recommended you create your own iconography
* Avoid icon fonts
* In order for SVG to adopt the same high contrast colour of the text, use currentColor.
* Icons should accompany either visible or visually hidden text label

### Implied

* Use the comprehensive and standardized set of BBC icons
* Use SVG icons
* There must be sufficient contrast between foreground icon colour and backgrounds, in line with WCAG 2.1 1.4.3 Contrast (Note: WCAG 2.1 1.4.11 Non-text Contrast is a more appropriate standard for iconography)
* States indicated using changes in icon styles must not be differented by colour alone

## Suggested ACT expectations

* SVG icons must take the focusable="false" attribution to remove them from focus order in some versions of IE and Edge
* There must be sufficient contrast between foreground icon colour and backgrounds, in line with WCAG 2.1 1.4.11 Non-text Contrast
* States indicated using changes in icon styles must not be differented by colour alone

**Comment by micmath** [comment]
Ready to go.
