### ISSUE TITLE
Grids

### ISSUE THREAD

**Issue by IanPouncey** [bbc/gel-test-docs#11]
https://bbc.github.io/gel/foundations/grids/

**Comment by IanPouncey** [comment]
## Extrapolation from GEL technical recommendations

### Required

* Table elements must not be allowed to wrap and find themselves falling under different headers.

### Recommended

* If items belong thematically to a set, mark them up as a list
* A page should make liberal but appropriate use of headings
* Avoid CSS Grid `order` property
* Avoiding fixed widths, set with width, so that grid content does not overflow
* Avoiding fixed heights, set with height, that would cause wrapped content to overlap
* Avoiding white-space: nowrap, which prevents text from wrapping

### Implied

* Use HTML landmark elements (`<main>`, `<aside>`, etc.) when appropriate
* Use `<div>` elements as grid container elements when there is no appropriate HTML landmark element
* Lists must not contain children that are not list items
* Do not use `<table>` elements for non-tabular content

## Suggested ACT expectations

* Table elements must not be allowed to wrap and find themselves falling under different headers.
* Do not use `<table>` elements for non-tabular content
* Semantic elements must be nested according to their specification

**Comment by micmath** [comment]
It's strange that our Grids documentation discusses Data Tables so much. We have a separate document for Data Tables.

**Comment by micmath** [comment]
This is good to go.
