### ISSUE TITLE
Cards

### ISSUE THREAD

**Issue by IanPouncey** [bbc/gel-test-docs#13]
https://bbc.github.io/gel/components/cards/

**Comment by IanPouncey** [comment]
## Extrapolation from GEL technical recommendations

### Required

* When cards are presented as a set, together they must be marked up as an unordered list, with each card marked as a list item (`<li>`)
* Each card's primary (headline) link must be contained within a heading
* Within a set, each of the card's headline headings must be of the same level, and the set of cards must be introduced as a section within the document by a heading one level higher.
* The element with class `gel-card__headline` must appear first in the source order within a card
* If a video is provided, ensure the following:
  * The video does not auto-play
  * The video player's controls are accessible by screen reader and keyboard
  * Dialogue in the video is accompanied by closed captions
* Quotations must be set out using the `<figure>` and `<figcaption>` elements. The `<figcaption>` element must come after the quotation itself
* Each card in a set should share the same height, despite content across cards varying in quantity/length
* Card layout must not be achieved using absolute positioning

### Recommended

* When an image is the focus of the card, it should be considered salient content and must include sufficient alternative text

### Implied

None

## Suggested ACT expectations

* When cards are presented as a set, together they must be marked up as an unordered list, with each card marked as a list item (`<li>`)
* Each card's primary (headline) link must be contained within a heading
* When an image is the focus of the card, it should be considered salient content and must include sufficient alternative text

**Comment by micmath** [comment]
This is good to go.
