### ISSUE TITLE
Focus

### ISSUE THREAD

**Issue by IanPouncey** [bbc/gel-test-docs#8]
https://bbc.github.io/gel/foundations/focus/

**Comment by IanPouncey** [comment]
## Extrapolation from GEL technical recommendations

### Required

* The body font-size must be adjustable by different means
* The body font-size must be between 15 and and 18 pixels, depending on the screen dimensions
* Be sure not to suppress zooming by touch on handheld devices
* Measure (line length) must be:
  * Set using an appropriate unit
  * Allowed to decrease in accordance with the width of its containing element
* Acronyms and initialisms must appear in all-caps
* Do not increase the letter-spacing of sentence-case text. 
* Links must not be differented by colour alone
* Provide links with an underline to differentiate them
* Do not underline non-link text

### Recommended

* The body font-size should always be set in relative units such as ems and rems.
* The root font-size should be set as a percentage of the user's chosen size, and all other sizes should be relative to this one.
* Your viewport meta tag should omit user-scalable=no
* You should not use justified text, instead align text along the left hand side
* Measure (line length) should be no more than 80 characters, but between 60 and 70 is better still
* Leading (line height) for body copy set in Reith Serif should be 1.375
* Leading (line height) should not be hard-coded using the px unit
* White space between a preceding section and a heading should be greater than the white space between the heading and the first paragraph of its own section
* Text set in all caps should be avoided in almost all cases
* Avoid placing text over complex images such as photographs
* Avoid unicode symbols in favor of SVG-based icons

### Implied

* There must be sufficient contrast between foreground text and backgrounds, in line with WCAG2.1 1.4.3 Contrast

## Suggested ACT expectations

* There must be sufficient contrast between foreground text and backgrounds, in line with WCAG 2.1 1.4.3 Contrast
* Do not suppress zooming by touch on handheld devices
* Acronyms and initialisms must appear in all-caps
* Links must not be differented by colour alone
* Do not underline non-link text

**Comment by thereadabilitygroup** [comment]
re "Provide a reasonably thick outline on focus that matches the text's colour" do I interpret that correctly that if the text was black then the focus outline should also be black? I've been looking [at the Gov.uk design guide](https://govuk-elements.herokuapp.com/form-elements/example-form-elements/) and they use a bright, contrasting colour for the focus outline. Wouldn't an easy-to-spot colour be better than black?

**Comment by micmath** [comment]
re "Provide a reasonably thick outline on focus that matches the text's colour" do I interpret that correctly that if the text was black then the focus outline should also be black? I've been looking [at the Gov.uk design guide](https://govuk-elements.herokuapp.com/form-elements/example-form-elements/) and they use a bright, contrasting colour for the focus outline. Wouldn't an easy-to-spot colour be better than black?

refers to:
> "In most circumstances, this should share the text's color (since the contrast for color should already differentiate it from the local background). Just omit a color value to achieve this."

**Comment by micmath** [comment]
I agree with the suggested ACT expectations.
